name: CI Pipeline

# Required GitHub Secrets:
# - VITE_CLERK_PUBLISHABLE_KEY: Your Clerk publishable key for frontend builds

on:
  push:
    branches: [ main, End-to-End-Unit-Testing ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Run unit tests
        run: npm run test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: coverage/
          retention-days: 30
          if-no-files-found: warn

  # E2E Tests with Playwright
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    
    env:
      # Environment variables for frontend build
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create .env file
        run: |
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" > .env

      - name: Build applications
        run: |
          npm run build:api
          npm run build:frontend

      - name: Start applications for testing
        run: |
          # Start API in background
          npm run start:api &
          # Start frontend in background  
          npm run start:frontend &
          # Wait for services to be ready
          sleep 10
        timeout-minutes: 2

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # Build check
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    
    env:
      # Environment variables for frontend build
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Create .env file
        run: |
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" > .env

      - name: Build all applications
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            apps/frontend/dist/
            apps/api/dist/
          retention-days: 7

  # Success notification
  notify-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests, build-check]
    if: success()
    
    steps:
      - name: Success notification
        run: |
          echo "✅ All tests passed!"
          echo "✅ Unit tests completed"
          echo "✅ E2E tests completed"
          echo "✅ Build check completed"
          echo "🚀 Ready for deployment when you're ready!"